# Generated by Django 5.2.7 on 2025-11-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('instructor', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('pausa', 'En Pausa'), ('cancelado', 'Cancelado')], default='disponible', max_length=20)),
            ],
        ),
    ]
