# Generated by Django 5.2.8 on 2025-12-04 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_criteriosseleccion_curriculumvitae_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_consecutivo', models.IntegerField()),
                ('instituto', models.CharField(blank=True, max_length=200)),
                ('nombre_curso', models.TextField(blank=True)),
                ('es_formacion', models.BooleanField(default=False)),
                ('es_actualizacion', models.BooleanField(default=False)),
                ('instructor', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('horas', models.IntegerField(blank=True, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=50)),
                ('docentes_inscritos', models.IntegerField(default=0)),
                ('docentes_terminaron', models.IntegerField(default=0)),
                ('docentes_acreditados', models.IntegerField(default=0)),
                ('tipo', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(default='Periodo Actual', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('jefe_desarrollo', models.CharField(blank=True, max_length=200)),
                ('subdirector', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroFormacion',
        ),
        migrations.AddField(
            model_name='diagnosticonecesidades',
            name='jefe1_depto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='diagnosticonecesidades',
            name='jefe1_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='diagnosticonecesidades',
            name='jefe2_depto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='diagnosticonecesidades',
            name='jefe2_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='diagnosticonecesidades',
            name='jefe3_depto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='diagnosticonecesidades',
            name='jefe3_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='diagnosticonecesidades',
            name='jefe4_depto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='diagnosticonecesidades',
            name='jefe4_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listaasistencia',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('finalizado', 'Finalizado')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='listaasistencia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrofila',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='Sistema.registrogeneral'),
        ),
    ]
