# Generated by Django 5.2.8 on 2025-12-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_registrofila_registrogeneral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC.')),
                ('curp', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('cct', models.CharField(blank=True, max_length=20, verbose_name='CCT')),
                ('municipio', models.CharField(max_length=200, verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['apellido_paterno', 'apellido_materno'],
            },
        ),
    ]
